import React from "react";

const words = [
  { word: "algorithm", hint: "A step-by-step procedure for solving a problem" },
  { word: "binary", hint: "A system of 0s and 1s used in computing" },
  { word: "compiler", hint: "A program that translates code into machine language" },
  { word: "debug", hint: "The process of fixing errors in code" },
  { word: "encrypt", hint: "To secure data by converting it into a code" },
  { word: "function", hint: "A reusable block of code that performs a task" },
  { word: "variable", hint: "A named storage in programming to hold data" },
  { word: "array", hint: "A collection of elements stored in a single variable" },
  { word: "loop", hint: "A way to repeat a block of code" },
  { word: "string", hint: "A sequence of characters enclosed in quotes" },
  { word: "object", hint: "An instance of a class in programming" },
  { word: "boolean", hint: "A data type with two values: true or false" },
  { word: "integer", hint: "A whole number, positive or negative" },
  { word: "recursion", hint: "When a function calls itself" },
  { word: "syntax", hint: "The rules for writing code in a programming language" },
  { word: "database", hint: "A structured collection of data" },
  { word: "framework", hint: "A platform for building software applications" },
  { word: "frontend", hint: "The part of a website users interact with" },
  { word: "backend", hint: "The server-side logic of a website" },
  { word: "server", hint: "A computer that provides data to other computers" },
  { word: "client", hint: "A computer or application that requests services" },
  { word: "developer", hint: "A person who writes and maintains code" },
  { word: "programmer", hint: "Another term for a developer" },
  { word: "software", hint: "Programs and other operating information used by a computer" },
  { word: "hardware", hint: "The physical components of a computer" },
  { word: "network", hint: "A group of interconnected computers" },
  { word: "protocol", hint: "Rules for data transmission in a network" },
  { word: "execute", hint: "To run a program or code" },
  { word: "compile", hint: "To convert source code into executable code" },
  { word: "optimize", hint: "To make a program run faster or use fewer resources" },
  { word: "iteration", hint: "A single loop cycle in programming" },
  { word: "stack", hint: "A data structure with LIFO (Last In, First Out)" },
  { word: "queue", hint: "A data structure with FIFO (First In, First Out)" },
  { word: "graph", hint: "A set of nodes connected by edges" },
  { word: "tree", hint: "A hierarchical data structure" },
  { word: "hashmap", hint: "A data structure that stores key-value pairs" },
  { word: "dynamic", hint: "Able to change during runtime" },
  { word: "static", hint: "Fixed and unchanging during runtime" },
  { word: "inheritance", hint: "When one class derives from another" },
  { word: "polymorphism", hint: "Ability to take many forms in programming" },
  { word: "encapsulation", hint: "Hiding internal details and showing only necessary parts" },
  { word: "abstraction", hint: "Focusing on what an object does, not how it does it" },
  { word: "module", hint: "A reusable piece of code in a program" },
  { word: "library", hint: "A collection of pre-written code for developers" },
  { word: "package", hint: "A bundle of related code and resources" },
  { word: "deployment", hint: "Releasing a software application to users" },
  { word: "testing", hint: "Checking a program for errors or bugs" },
  { word: "refactor", hint: "Improving code without changing its behavior" },
  { word: "pseudocode", hint: "An informal way of programming description" },
  { word: "runtime", hint: "The time during which a program is running" },
  { word: "constraint", hint: "A limitation or condition in a problem" },
  { word: "greedy", hint: "An algorithm that makes the locally optimal choice" },
  { word: "complexity", hint: "A measure of time or space an algorithm takes" },
  { word: "bigO", hint: "Describes the performance of an algorithm" },
  { word: "competitive", hint: "Programming contests for solving problems" },
  { word: "leetcode", hint: "A popular platform for coding practice" },
  { word: "hackerrank", hint: "A platform for coding and interview preparation" },
  { word: "repository", hint: "A storage location for code, often in Git" },
  { word: "commit", hint: "Saving changes in a version control system" },
  { word: "clone", hint: "Copying a repository to your local machine" },
  { word: "merge", hint: "Combining changes from different branches" },
  { word: "branch", hint: "A separate version of a codebase" },
  { word: "pull", hint: "Fetching and merging changes from a repository" },
];


export default function chooseRandom() {

  // Correct random selection
  const randomIndex = Math.floor(Math.random() * words.length);
  const randomWord = words[randomIndex];

  return randomWord;
}
